server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://pxc-bjr75hj5p88da9.polarx.rds.aliyuncs.com:3306/galaxy_map_test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: galaxy_map_test
    password: Kiufew8847rstw
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      # 初始化大小，最小，最大
      initial-size: 5
      minIdle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
  redis:
    host: r-2zelvgpc6la6v7xrrf.redis.rds.aliyuncs.com
    port: 6379
    password: LdZ4xu7mzmHYBnqd
    database: 0
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
